# Generated by Django 4.1.4 on 2022-12-25 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crawler", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="websitedata",
            name="session",
        ),
        migrations.AddField(
            model_name="crawljob",
            name="session",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
