# Generated by Django 4.1.4 on 2022-12-25 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crawler", "0002_remove_websitedata_session_crawljob_session"),
    ]

    operations = [
        migrations.RenameField(
            model_name="websitedata",
            old_name="website",
            new_name="url",
        ),
    ]
